version: "3.8"

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: telecom
      POSTGRES_USER: telecom
      POSTGRES_PASSWORD: telecompass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/telecom
      SPRING_DATASOURCE_USERNAME: telecom
      SPRING_DATASOURCE_PASSWORD: telecompass

      APP_JWT_SECRET: ${APP_JWT_SECRET}
      APP_JWT_EXP_MS: 3600000
      APP_AUTH_ALLOW_REGISTER: true

      SPRING_PROFILES_ACTIVE: dev

volumes:
  pgdata:
